# Generated by Django 5.0.3 on 2024-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='family_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
